version: '3.4'

services:
    catalogdb:
        image: "postgres"
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=CatalogDb
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
          context: .
          dockerfile: Catalog.Api/Dockerfile

volumes:
    postgres_catalog:
        name: "postgres_catalog"
