services:
  catalogdb:
    container_name: catalogdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres; 
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

# services:
#   catalog.api:
#     image: catalog.api
#     depends_on:
#       - catalogdb
#     ports: 
#       - "6000:8080"
#       - "6060:8081" 
#     networks:
#       - app-network
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_HTTP_PORTS=8080
#       - ASPNETCORE_HTTPS_PORTS=8081
#       - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres;

#   catalogdb:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_DB: CatalogDb
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     networks:
#       - app-network
#     volumes:
#       - postgres_catalog:/var/lib/postgresql/data
# networks:
#   app-network: