version: '3.4'

services:
    catalogdb:
        image: "postgres"
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=CatalogDb

volumes:
    postgres_catalog:
        name: "postgres_catalog"